### ISSUE TITLE
Plan - dat_container_runtime

### ISSUE THREAD

**Issue by alyhxn** [serapath/task-messenger#13]
## todo

- Plan - dat_container_runtime
   - [x] Discussion - `2h`
   - [x] Understanding the code - `4h`
   
- Update - dat_container_runtime
   - [ ] Get rid of budo and browserify
   - [ ] Implement shortcuts described here [discord_msg](https://discord.com/channels/859134561018839060/1246470040954474588/1246944387578204172)
   - [ ] Save the state of all vaults
   - [ ] Implement settings for `devtools-vault` which display ana and bobs data/stats/communication and gives controls

**Comment by alyhxn** [comment]
### tasks - `2024.06.04`
- Plan - dat_container_runtime
   - `@input` :package: [discord_thread](https://discord.com/channels/859134561018839060/1246470040954474588)
   - Discussion - `2h`
   - Understanding the code - `4h`
   - Repaired `ana-test` and `bob-test` fake connection - `2h`
   - Logged tasks - `10min`
   - `@output` :package: [dat_container_runtime_v0.0.1](https://github.com/serapath/task-messenger/commit/8bd5d54fa7f8f224c6f142027f984f01c7d05c24)

**Comment by alyhxn** [comment]
### tasks - `2024.06.05`
- Update - dat_container_runtime_v0.0.1
   - Setup the `localStorage` through `MessageChannel` - `3h`
   - Logged tasks and recorded video - `10min`
   - `@output` :package: [dat_container_runtime_v0.0.2](https://github.com/serapath/task-messenger/commit/1311be64d902f3a0bd237d9f8da7a3be62d3ceae)
   
---

### Worklog
[worklog-211](https://youtu.be/mtlT7oboQy8)

**Comment by serapath** [comment]
**feedback `2024.06.05`**

I havent looked at the actual code DIFF yet and am waiting for the pull request, so the following feedback is based on the worklog video alone.

![getset](https://imgur.com/tXuxheh.png)
and
![useget](https://imgur.com/FBhcT84.png)

If the `get` call in the second screenshot is the same as the `function get` in the first one, then i wonder what is supposed to happen here.

The `.postMessage` call does not return anything.
Any potential message that gets send back by the receiver ot the posmessage will be received in the `port.onmessage = event => {}` function.

So the back and forth is quite a bit more involved then who this what i see here is maybe assumed to work :-)
