### ISSUE TITLE
Create - devtools

### ISSUE THREAD

**Issue by alyhxn** [serapath/task-messenger#6]
## todo

- [ ] Create - devtools
   - `@input` :package: [dicord_msg](https://discord.com/channels/859134561018839060/1235708415322361966/1239731523263922259)
   - [x] Setup and code copy/paste devtools - `20min`
   - [x] p2p data structure experimentation - `20h`
   - [x] Created and logged tasks - `5min`
   - `@output` :package: [devtools](https://github.com/alyhxn/task-messenger/commit/1c2d17cf86e5d7caba4ba89f2af25a734b0e69a9) from [comment]()
