### ISSUE TITLE
Create - SPEC.md

### ISSUE THREAD

**Issue by alyhxn** [serapath/task-messenger#7]
## todo

- [ ] Create SPEC.md
   - [x] Initial details - `15min`
   - [x] Summary - `30min`
   - [x] p2p data structure experimentation - `20h`
   - `@output` :package: [SPEC.md_v0.0.1](https://github.com/alyhxn/task-messenger/commit/3e55424ea4dfa2d0c2ecaec1136426ae178b00e7) from [comment]()

**Comment by alyhxn** [comment]
### tasks - `2024.05.14`

- Create SPEC.md
   - Initial details - `15min`
   - Summary - `30min`
   - p2p data structure experimentation - `20h`
   - Logged tasks - `5min`
   - `@output` :package: [SPEC.md_v0.0.1](https://github.com/alyhxn/task-messenger/commit/3e55424ea4dfa2d0c2ecaec1136426ae178b00e7)

### feedback
I have nothing to say :disappointed:

**Comment by alyhxn** [comment]
### tasks - `2024.05.17`

- Update SPEC.md_v0.0.1
   - Added p2p modules - `5min
   - Split into SPEC_p2p and SPEC_TM - `5min`
   - Added more content to SPEC_p2p - `1h30min`
   - Added content to SPEC_TM - `12min`
   - Logged tasks - `7min`
   - @output :package: [SPEC_p2p_v0.0.2](https://github.com/alyhxn/task-messenger/commit/1944762fad1a9debe4f2dd4515f8ec74247a1b8c#diff-7e3325b178102feb24ebb77df721d7511a4e701400cbf7f798653e77dbee3fe3)
   - @output :package: [SPEC_TM_v0.0.2](https://github.com/alyhxn/task-messenger/commit/1944762fad1a9debe4f2dd4515f8ec74247a1b8c#diff-c236206fca3f7b20f4cf1870319af1b2bb7292ca641471ec261657bc013da292)
   
### Feedback
- I have all the p2p modules exercise code as it is. They can't be previewed anywhere functioning.
- If you want quick work, you can tell me explicitly, that will work like adrenaline in my brain.
